### PR TITLE
Update docs for x-api v3

### PR DESCRIPTION
**Pull request by kytrinyx**
@canweriotnow this is a half-baked thing.

I'm ditching the help site (powered by the github.com/exercism/docs repository), and putting all the getting started stuff in each of the language repositories where it's easier for people to maintain (belongs with the language, it seems like).

Instead, I'm pulling in the documentation for each track from the API, and showing it on the individual language pages (PR here: https://github.com/exercism/exercism.io/pull/2628)

Anyway, the x-api now serves the docs as markdown (I still have to figure out how to translate the orgmode stuff to markdown or html so that the site can consume it, but that's minor).

Would you mind taking a stab at fixing this to be proper orgmode?

### CODE REVIEW

**Comment by yurrriq** [comment]
@kytrinyx @canweriotnow if I find time I can org-ify this tonight.

**Comment by kytrinyx** [comment]
That would be great!

**Comment by yurrriq** [comment]
I fixed a type too: `s/info/intro/`

**Comment by yurrriq** [comment]
- [pandoc](http://pandoc.org) can handle the translation:
  ```sh
  pandoc -f org -t markdown_github {{FILENAME}}.org -o {{FILENAME}}.md
  ```

- Within Emacs, I use and :heart: [ox-gfm](https://github.com/larstvei/ox-gfm).
- Or, since I think you use Ruby, [org-ruby](https://github.com/wallyqs/org-ruby) might be useful.

**Comment by kytrinyx** [comment]
Nice! I actually have both pandoc and ruby installed locally, so I should be all good to go.

**Comment by canweriotnow** [comment]
@yurrriq thanks for handling this!

@kytrinyx if you're doing it within the API, org-ruby is probably a good bet as you can translate org->md (and html, etc.) on-the-fly within the application instead of having to pre-translate through pandoc.

**Comment by yurrriq** [comment]
No problem! :+1: for org-ruby on the fly.

**Comment by kytrinyx** [comment]
Yeah, I created an issue for that: https://github.com/exercism/x-api/issues/79

**Pull request merged**
